!classDefinition: #MarsRoverLoggerTest category: 'MarsRover-WithHeading'!
TestCase subclass: #MarsRoverLoggerTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverLoggerTest methodsFor: 'auxiliary'!
! !

!MarsRoverLoggerTest methodsFor: 'auxiliary'!
! !

!MarsRoverLoggerTest methodsFor: 'auxiliary'!
! !

!MarsRoverLoggerTest methodsFor: 'auxiliary'!
! !


!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !

!MarsRoverLoggerTest methodsFor: 'tests'!
! !


!classDefinition: #MarsRoverStateWindowTest category: 'MarsRover-WithHeading'!
TestCase subclass: #MarsRoverStateWindowTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverStateWindowTest methodsFor: 'auxiliary'!
! !

!MarsRoverStateWindowTest methodsFor: 'auxiliary'!
! !

!MarsRoverStateWindowTest methodsFor: 'auxiliary'!
! !

!MarsRoverStateWindowTest methodsFor: 'auxiliary'!
! !

!MarsRoverStateWindowTest methodsFor: 'auxiliary'!
! !

!MarsRoverStateWindowTest methodsFor: 'auxiliary'!
! !

!MarsRoverStateWindowTest methodsFor: 'auxiliary'!
! !

!MarsRoverStateWindowTest methodsFor: 'auxiliary'!
! !

!MarsRoverStateWindowTest methodsFor: 'auxiliary'!
! !


!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !

!MarsRoverStateWindowTest methodsFor: 'tests'!
! !


!classDefinition: #MarsRoverTest category: 'MarsRover-WithHeading'!
TestCase subclass: #MarsRoverTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !

!MarsRoverTest methodsFor: 'tests'!
! !


!MarsRoverTest methodsFor: 'headings'!
! !

!MarsRoverTest methodsFor: 'headings'!
! !

!MarsRoverTest methodsFor: 'headings'!
! !

!MarsRoverTest methodsFor: 'headings'!
! !


!MarsRoverTest methodsFor: 'assertions'!
! !


!classDefinition: #MarsRover category: 'MarsRover-WithHeading'!
Object subclass: #MarsRover
	instanceVariableNames: 'position head positionFollowers headingFollowers'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRover methodsFor: 'command processing'!
! !

!MarsRover methodsFor: 'command processing'!
! !


!MarsRover methodsFor: 'exceptions'!
! !

!MarsRover methodsFor: 'exceptions'!
! !


!MarsRover methodsFor: 'heading'!
! !

!MarsRover methodsFor: 'heading'!
! !

!MarsRover methodsFor: 'heading'!
! !

!MarsRover methodsFor: 'heading'!
! !

!MarsRover methodsFor: 'heading'!
! !

!MarsRover methodsFor: 'heading'!
! !

!MarsRover methodsFor: 'heading'!
! !


!MarsRover methodsFor: 'initialization'!
! !


!MarsRover methodsFor: 'moving'!
! !

!MarsRover methodsFor: 'moving'!
! !

!MarsRover methodsFor: 'moving'!
! !

!MarsRover methodsFor: 'moving'!
! !

!MarsRover methodsFor: 'moving'!
! !

!MarsRover methodsFor: 'moving'!
! !

!MarsRover methodsFor: 'moving'!
! !


!MarsRover methodsFor: 'testing'!
! !

!MarsRover methodsFor: 'testing'!
! !

!MarsRover methodsFor: 'testing'!
! !

!MarsRover methodsFor: 'testing'!
! !

!MarsRover methodsFor: 'testing'!
! !


!MarsRover methodsFor: 'visitors'!
! !

!MarsRover methodsFor: 'visitors'!
! !

!MarsRover methodsFor: 'visitors'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'MarsRover class' category: 'MarsRover-WithHeading'!
MarsRover class
	instanceVariableNames: 'headings'!

!MarsRover class methodsFor: 'instance creation'!
! !


!classDefinition: #MarsRoverFollower category: 'MarsRover-WithHeading'!
Object subclass: #MarsRoverFollower
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverFollower methodsFor: 'operations'!
! !

!MarsRoverFollower methodsFor: 'operations'!
! !


!MarsRoverFollower methodsFor: 'visiting'!
! !

!MarsRoverFollower methodsFor: 'visiting'!
! !

!MarsRoverFollower methodsFor: 'visiting'!
! !

!MarsRoverFollower methodsFor: 'visiting'!
! !

!MarsRoverFollower methodsFor: 'visiting'!
! !

!MarsRoverFollower methodsFor: 'visiting'!
! !

!MarsRoverFollower methodsFor: 'visiting'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'MarsRoverFollower class' category: 'MarsRover-WithHeading'!
MarsRoverFollower class
	instanceVariableNames: ''!

!MarsRoverFollower class methodsFor: 'instance creation'!
! !

!MarsRoverFollower class methodsFor: 'instance creation'!
! !

!MarsRoverFollower class methodsFor: 'instance creation'!
! !


!classDefinition: #MarsRoverLogger category: 'MarsRover-WithHeading'!
MarsRoverFollower subclass: #MarsRoverLogger
	instanceVariableNames: 'log'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverLogger methodsFor: 'initialization'!
! !


!MarsRoverLogger methodsFor: 'operations'!
! !

!MarsRoverLogger methodsFor: 'operations'!
! !

!MarsRoverLogger methodsFor: 'operations'!
! !


!MarsRoverLogger methodsFor: 'visiting'!
! !

!MarsRoverLogger methodsFor: 'visiting'!
! !

!MarsRoverLogger methodsFor: 'visiting'!
! !

!MarsRoverLogger methodsFor: 'visiting'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'MarsRoverLogger class' category: 'MarsRover-WithHeading'!
MarsRoverLogger class
	instanceVariableNames: ''!

!MarsRoverLogger class methodsFor: 'instance creation'!
! !

!MarsRoverLogger class methodsFor: 'instance creation'!
! !


!classDefinition: #MarsRoverStateWindow category: 'MarsRover-WithHeading'!
MarsRoverFollower subclass: #MarsRoverStateWindow
	instanceVariableNames: 'heading position'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverStateWindow methodsFor: 'accessing'!
! !

!MarsRoverStateWindow methodsFor: 'accessing'!
! !


!MarsRoverStateWindow methodsFor: 'initialization'!
! !


!MarsRoverStateWindow methodsFor: 'operations'!
! !


!MarsRoverStateWindow methodsFor: 'visiting'!
! !

!MarsRoverStateWindow methodsFor: 'visiting'!
! !

!MarsRoverStateWindow methodsFor: 'visiting'!
! !

!MarsRoverStateWindow methodsFor: 'visiting'!
! !


!MarsRoverStateWindow methodsFor: 'visiting - private'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'MarsRoverStateWindow class' category: 'MarsRover-WithHeading'!
MarsRoverStateWindow class
	instanceVariableNames: ''!

!MarsRoverStateWindow class methodsFor: 'instance creation'!
! !

!MarsRoverStateWindow class methodsFor: 'instance creation'!
! !


!classDefinition: #MarsRoverHeading category: 'MarsRover-WithHeading'!
Object subclass: #MarsRoverHeading
	instanceVariableNames: 'marsRover'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverHeading methodsFor: 'heading'!
! !

!MarsRoverHeading methodsFor: 'heading'!
! !


!MarsRoverHeading methodsFor: 'initialization'!
! !


!MarsRoverHeading methodsFor: 'moving'!
! !

!MarsRoverHeading methodsFor: 'moving'!
! !


!MarsRoverHeading methodsFor: 'testing'!
! !


!MarsRoverHeading methodsFor: 'visitors'!
! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'MarsRoverHeading class' category: 'MarsRover-WithHeading'!
MarsRoverHeading class
	instanceVariableNames: ''!

!MarsRoverHeading class methodsFor: 'instance creation'!
! !


!classDefinition: #MarsRoverHeadingEast category: 'MarsRover-WithHeading'!
MarsRoverHeading subclass: #MarsRoverHeadingEast
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverHeadingEast methodsFor: 'moving'!
! !

!MarsRoverHeadingEast methodsFor: 'moving'!
! !


!MarsRoverHeadingEast methodsFor: 'heading'!
! !

!MarsRoverHeadingEast methodsFor: 'heading'!
! !


!MarsRoverHeadingEast methodsFor: 'visitors'!
! !


!classDefinition: #MarsRoverHeadingNorth category: 'MarsRover-WithHeading'!
MarsRoverHeading subclass: #MarsRoverHeadingNorth
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverHeadingNorth methodsFor: 'moving'!
! !

!MarsRoverHeadingNorth methodsFor: 'moving'!
! !


!MarsRoverHeadingNorth methodsFor: 'heading'!
! !

!MarsRoverHeadingNorth methodsFor: 'heading'!
! !


!MarsRoverHeadingNorth methodsFor: 'visitors'!
! !


!classDefinition: #MarsRoverHeadingSouth category: 'MarsRover-WithHeading'!
MarsRoverHeading subclass: #MarsRoverHeadingSouth
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverHeadingSouth methodsFor: 'moving'!
! !

!MarsRoverHeadingSouth methodsFor: 'moving'!
! !


!MarsRoverHeadingSouth methodsFor: 'heading'!
! !

!MarsRoverHeadingSouth methodsFor: 'heading'!
! !


!MarsRoverHeadingSouth methodsFor: 'visitors'!
! !


!classDefinition: #MarsRoverHeadingWest category: 'MarsRover-WithHeading'!
MarsRoverHeading subclass: #MarsRoverHeadingWest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MarsRover-WithHeading'!

!MarsRoverHeadingWest methodsFor: 'moving'!
! !

!MarsRoverHeadingWest methodsFor: 'moving'!
! !


!MarsRoverHeadingWest methodsFor: 'heading'!
! !

!MarsRoverHeadingWest methodsFor: 'heading'!
! !


!MarsRoverHeadingWest methodsFor: 'visitors'!
! !
